language: ruby
sudo:     false
cache:    bundler
script:   bundle exec rake test

before_install:
  - gem i bundler -v=1.10.3

before_script:
  - psql -c 'create database activerecord_correctable;' -U postgres

rvm:
  - 2.1
  - 2.2.2
  - ruby-head

gemfile:
  - gemfiles/activerecord_40.gemfile
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_42.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DATABASE_ADAPTER=sqlite3
  - DATABASE_ADAPTER=postgres
  # - DATABASE_ADAPTER=mysql2

matrix:

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_edge.gemfile
  fast_finish: true
