language: ruby
sudo:     false
cache:    bundler
script:   bundle exec rake test

before_install:
  - gem i bundler
  - gem uni did_you_mean -v=1.0.0

before_script:
  - psql -c 'create database did_you_mean_activerecord;' -U postgres

rvm:
  - 2.4.0
  - 2.3.3
  - ruby-head
  - jruby-9.1.6.0

gemfile:
  - gemfiles/activerecord_50.gemfile
  - gemfiles/activerecord_42.gemfile
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DATABASE_ADAPTER=sqlite3
  - DATABASE_ADAPTER=postgres
  # - DATABASE_ADAPTER=mysql2

matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/activerecord_41.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/activerecord_42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_41.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.6.0
    - gemfile: gemfiles/activerecord_edge.gemfile
